// <auto-generated />
namespace Hotellerie_Amine_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AjoutNoteApprec : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjoutNoteApprec));
        
        string IMigrationMetadata.Id
        {
            get { return "202001041431075_AjoutNoteApprec"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
